### ISSUE TITLE
Support multiple schemas applying to different portions of a VC

### ISSUE THREAD

**Issue by decentralgabe** [w3c-ccg/vc-json-schemas#121]
Consider a credential pointing to a single VC JSON Schema identified `https://example.org/examples/verifiable-credential-schema.json`

```json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://www.w3.org/2018/credentials/examples/v1"
  ],
  "id": "http://example.edu/credentials/3732",
  "type": ["VerifiableCredential", "UniversityDegreeCredential"],
  "issuer": "https://example.edu/issuers/14",
  "issuanceDate": "2010-01-01T19:23:24Z",
  "credentialSubject": {
    "id": "did:example:ebfeb1f712ebc6f1c276e12ec21",
    "degree": {
      "type": "BachelorDegree",
      "name": "Bachelor of Science and Arts"
    }
  },
  "credentialSchema": {
    "id": "https://example.org/examples/verifiable-credential-schema.json",
    "type": "CredentialSchema2022"
  }
}
```

This schema resolves to a document such as

```json
{
    "type": "https://w3c-ccg.github.io/vc-json-schemas/schema/2.0/schema.json",
    "version": "1.0",
    "id": "did:example:MDP8AsFhHzhwUvGNuYkX7T/06e126d1-fa44-4882-a243-1e326fbe21db?version=1.0",
    "name": "Email",
    "author": "did:example:MDP8AsFhHzhwUvGNuYkX7T",
    "authored": "2022-05-05T00:00:00+00:00",
    "path": "$.credentialSubject",
    "schemas":
    [
        {
            "path": "$.credentialSubject",
            "schema":
            {
                "$id": "name-schema-1.0",
                "$schema": "https://json-schema.org/draft/2019-09/schema",
                "description": "Name",
                "type": "object",
                "properties":
                {
                    "firstName":
                    {
                        "type": "string"
                    },
                    "lastName":
                    {
                        "type": "string"
                    }
                },
                "required":
                [
                    "firstName",
                    "lastName"
                ],
                "additionalProperties": false
            }
        },
        {
            "path": "$.credentialSubject",
            "schema":
            {
                "$id": "email-schema-1.0",
                "$schema": "https://json-schema.org/draft/2019-09/schema",
                "description": "Email",
                "type": "object",
                "properties":
                {
                    "emailAddress":
                    {
                        "type": "string",
                        "format": "email"
                    }
                },
                "required":
                [
                    "emailAddress"
                ],
                "additionalProperties": false
            }
        }
    ]
}
```

In this way a single VC JSON Schema can embed multiple schemas in a single document which apply to the same (or perhaps different) part(s) of a credential.

**Comment by David-Chadwick** [comment]
Could you please explain the benefit of doing what you propose, as opposed to using one schema language to define the entire schema for the VC, and optionally a different schema language to do the same thing.

**Comment by andresuribe87** [comment]
@David-Chadwick just making sure I understand your alternative. 

> using one schema language to define the entire schema for the VC, and optionally a different schema language to do the same thing.

Is something like the following what you're proposing? The below design implies that the schema would _always_ be used to validate the value of the `credentialSubject` property of the VC. 

```json
{
    "type": "https://w3c-ccg.github.io/vc-json-schemas/schema/2.0/schema.json",
    "version": "1.0",
    "id": "did:example:MDP8AsFhHzhwUvGNuYkX7T/06e126d1-fa44-4882-a243-1e326fbe21db?version=1.0",
    "name": "Email",
    "author": "did:example:MDP8AsFhHzhwUvGNuYkX7T",
    "authored": "2022-05-05T00:00:00+00:00",
    "schema": {
        "allOf":
        [
              {
                  "$id": "name-schema-1.0",
                  "$schema": "https://json-schema.org/draft/2019-09/schema",
                  "description": "Name",
                  "type": "object",
                  "properties":
                  {
                      "firstName":
                      {
                          "type": "string"
                      },
                      "lastName":
                      {
                          "type": "string"
                      }
                  },
                  "required":
                  [
                      "firstName",
                      "lastName"
                  ]
              },
              {
                  "$id": "email-schema-1.0",
                  "$schema": "https://json-schema.org/draft/2019-09/schema",
                  "description": "Email",
                  "type": "object",
                  "properties":
                  {
                      "emailAddress":
                      {
                          "type": "string",
                          "format": "email"
                      }
                  },
                  "required":
                  [
                      "emailAddress"
                  ]
              }
        ]
    }
}
```

**Comment by David-Chadwick** [comment]
No, this is what I was trying to say

```

	"credentialSchema": [{
		"id": "https://example.org/examples/verifiable-credential-schema22.json",
		"type": "CredentialSchema2022"
	}, {
		"id": "https://example.org/examples/verifiable-credential-schema23.json",
		"type": "CredentialSchema2023"
	}]
```
the credentialSchema should be a set of objects, where each object refers to one schema language and the` id` points to the location of the schema definition for this VC

**Comment by andresuribe87** [comment]
That's a valid point, but I don't follow how that addresses supporting multiple schemas to different portions of a VC. Would you mind elaborating? 

Separately, where would the `author` and `authored ` properties be defined in your proposal?

**Comment by David-Chadwick** [comment]
> how that addresses supporting multiple schemas to different portions of a VC. 

It doesn't. Because I do not see the point in that. Could you please answer my original question. "Could you please explain the benefit of doing what you propose"

**Comment by decentralgabe** [comment]
@David-Chadwick theres a schema for the entire VCDM. There's another for the credentialSubject. Perhaps another for evidence, and so on. It's simpler and better architectural practice to decompose these schemes to promote reusability and determine which validations pass with finer grain precision.

Putting all schemas in the credential itself is confusing, because then we'll need to define processing logic: the order of evaluation, which determine failure, how to handle overlap, etc. These concerns are better to be handled in a specific schema type definition, which is why I recommended keeping the property a single value and handling the complexity in specific types.

**Comment by David-Chadwick** [comment]
I take the point that engineers that define a specific property e.g. Evidence, may also define the schema for it. Let's call this a sub-schema of a VC. But I do not accept that combining multiple sub-schemas together into the schema for a particular VC is confusing since the schema processing code can now evaluate the entire VC in one pass. Your alternative, I think (forgive me if I am wrong) is to call several different sub-schema processing routines. I would say is more confusing. The bottom line is that the issuer either creates a VC that conforms to the VC's schema, or does not conform. You appear to be wanting to add shades of grey: e.g. this VC conforms to the sub-schemas of the VC DM and ToU, but not to the Evidence and Status sub-schemas. What should a recipient make of this?

**Comment by decentralgabe** [comment]
I've outlined the reasons I believe it to be architecturally unsound to combine sub-schemas together. Amending an authoritative schema [such as the one in this repo](https://github.com/w3c/vc-data-model/blob/main/schema/verifiable-credential/verifiable-credential-schema.json) should not be done via direct modification, but inclusion of finer-grained schemas.

It is far less confusing to see multiple schemas applying to different parts of a credential than a giant schema with overlapping purposes. With the suggested approach you get finer-grained error messages and control over what verification/validation means, too.

A recipient is able to do the verification and validation they care to do. This already happens today. Keeping this validation at the property-level makes sense, generally.

**Comment by David-Chadwick** [comment]
I guess we will just have to disagree on this.

**Comment by decentralgabe** [comment]
That is fine. The beauty of extension is being able to define different `type`s to fit different purposes.

**Comment by decentralgabe** [comment]
There are two main options we should discuss.

# Option 1: Using JSON Path

```{
  "schemas": [
    {
      "path": "$",
      "schema": {
        "$ref": "https://raw.githubusercontent.com/w3c/vc-data-model/main/schema/verifiable-credential/verifiable-credential-schema.json"
      }
    },
    {
      "path": "$.credentialSubject",
      "schema": {
        "$id": "name-schema-1.0",
        "$schema": "https://json-schema.org/draft/2019-09/schema",
        "description": "Name",
        "type": "object",
        "properties": {
          "firstName": {
            "type": "string"
          },
          "lastName": {
            "type": "string"
          }
        },
        "required": [
          "firstName",
          "lastName"
        ],
        "additionalProperties": false
      }
    },
    {
      "path": "$.credentialSubject",
      "schema": {
        "$id": "email-schema-1.0",
        "$schema": "https://json-schema.org/draft/2019-09/schema",
        "description": "Email",
        "type": "object",
        "properties": {
          "emailAddress": {
            "type": "string",
            "format": "email"
          }
        },
        "required": [
          "emailAddress"
        ],
        "additionalProperties": false
      }
    }
  ]
}```

# Option 2: One schema

```
{
  "allOf": [
    {
      "$ref": "https://raw.githubusercontent.com/w3c/vc-data-model/main/schema/verifiable-credential/verifiable-credential-schema.json"
    },
    {
      "$id": "name-schema",
      "$schema": "https://json-schema.org/draft/2019-09/schema",
      "description": "Name",
      "type": "object",
      "properties": {
        "credentialSubject": {
          "type": "object",
          "properties": {
            "name": {
              "type": "object",
              "properties": {
                "firstName": {
                  "type": "string"
                },
                "lastName": {
                  "type": "string"
                },
                "additionalProperties": false
              },
              "required": [
                "firstName",
                "lastName"
              ]
            }
          }
        }
      }
    },
    {
      "$id": "email-schema-1.0",
      "$schema": "https://json-schema.org/draft/2019-09/schema",
      "description": "Email",
      "type": "object",
      "properties": {
        "credentialSubject": {
          "type": "object",
          "properties": {
            "email": {
              "type": "object",
              "properties": {
                "emailAddress": {
                  "type": "string",
                  "format": "email"
                }
              },
              "required": [
                "emailAddress"
              ],
              "additionalProperties": false
            }
          }
        }
      }
    }
  ]
}
```
