### ISSUE TITLE
Fix credential-schema links

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/vc-json-schemas#13]
`"type": "https://credentials.workday.com/docs/credential-schema.json"`

This should point to this repo and resolve to something.

**Comment by glcohen** [comment]
This should do it https://credentials.workday.com/docs/specification/v1.0/schema.json

**Comment by glcohen** [comment]
https://github.com/w3c-ccg/vc-json-schemas/pull/15

**Comment by glcohen** [comment]
Links are amended
