### ISSUE TITLE
Document usage flows

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/vc-json-schemas#14]
Now that VCs can have a credential schema, its time to describe how it is used.

I think its natural to validate an incoming payload against the schema before issuing it, this is similar to the use of JSON Schema as middleware in http servers.

For credentials that are not planning on using JSON-LD, this schema checking should probably happen before emitting the credential and before consuming it. This use case is less clear to me.

**Comment by glcohen** [comment]
Agree on validation, it will be an important addition + examples in multiple languages. https://github.com/w3c-ccg/vc-json-schemas/issues/11

**Comment by decentralgabe** [comment]
There is now a section on processing which speaks to this issue handled in #123
