### ISSUE TITLE
Why do we need two schema system/languages?

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/vc-json-schemas#16]
Since the linked data context for the vc and the json schema for the vc serve similar purposes, how should we describe the decision to support both?

Which is more authoritative?

May be worth investigating some of the type transformation that JSON Schema supports that JSON-LD does not.

**Comment by glcohen** [comment]
By the [language in the spec](https://github.com/w3c-ccg/vc-json-schemas/issues/17) the context in the VC does not necessarily provide the information about the `credentialSubject`. 

Similarly, the context in the schema may not include much information at all (if they are there simply to comply with the spec for the sake of interop with those who choose to use LD).

In the perfect LD-everywhere usage of the ecosystem there is overlap. In the other extreme, both properties could serve a purpose, or none at all.

**Comment by VladimirAlexiev** [comment]
JSON-LD is not a schema system/language, whereas JSON Schema does not provide global meaning to data. 
So yes, both are useful. See #88 for details

**Comment by TallTed** [comment]
Please retitle to _"Why do we need **two** schema systems?"_ so "schema" doesn't read as a verb acting on "systems".

**Comment by decentralgabe** [comment]
there is a section on using both LD and JSON Schema together, it could use some more work so I will keep this open. looking for volunteers 😄

**Comment by decentralgabe** [comment]
Closing to be handled in #122
