### ISSUE TITLE
Summary of "forks" from VC spec

### ISSUE THREAD

**Issue by troyronda** [w3c-ccg/vc-json-schemas#18]
From https://w3c-ccg.github.io/vc-json-schemas/#standards_compliance
> W3C specification is under active development and is subject to change, we have diverged from that model with several "forks" that are fully outlined in this specification.

Is there a summary of these "forks"? I wasn't entirely sure of the "fork" list after reading the document.

**Comment by glcohen** [comment]
The main fork was not including a `@context` property. That will likely be changing (see https://github.com/w3c-ccg/vc-json-schemas/issues/7). The section should be amended.

**Comment by decentralgabe** [comment]
This section needs to be updated to state how the `credentialSchema` section of the VCDM is intended to be used with this spec.

**Comment by decentralgabe** [comment]
Handled by #121
