### ISSUE TITLE
Fix proof / JSON-LD compatibility issues

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/vc-json-schemas#2]
See Comments on: https://github.com/w3c-ccg/vc-json-schemas/pull/1

We need to construct an example which does not use JSON-LD, and document the necessary steps for other signatures to be created.

We also need to do the same for JSON-LD... I feel it may be easier to do the JSON-LD version first, since its basically an issue of just using an off the shelf library.

**Comment by OR13** [comment]
IMO, based on the current data model described in the spec, it will be easier to make a JSON-LD version first.

We can then define our own Linked Data Signature suite that uses json stringify deterministic and JOSE / JWS Detached Signatures... 

https://w3c-dvcg.github.io/ld-signatures/#create-verify-hash-algorithm

This proof object:

```
  "proof": {
      "created": "2019-09-27T06:26:11Z",
      "creator": "did:work:MDP8AsFhHzhwUvGNuYkX7T#key-1",
      "nonce": "0efba23d-2987-4441-998e-23a9d9af79f0",
      "signatureValue": "2A7ZF9f9TWMdtgn57Y6dP6RQGs52xg2QdjUESZUuf4J9BUnwwWFNL8vFshQAEQF6ZFBXjYLYNU4hzXNKc3R6y6re",
      "type": "Ed25519VerificationKey2018"
  }
```

Looks so much like JSON-LD  that imo we need to make a proper JSON-LD Signature for what is happening here...see: https://medium.com/swlh/json-web-signature-jws-and-jws-detached-for-a-five-year-old-88729b7b1a68

The linked data signature would describe how we remove proof.signatureValue (or jws)... Then stringify and base64url encode the schema before reassembling the the JWS in its normal form of:

`protected.payload.signature`

Since what I'm describing is not standard, I think its best described by actually creating a JSON-LD Signature suite (what I am saying is a valid approach for such a suite).

Consumers who don't care about JSON-LD need to read the docs to understand how the proof works, and they won't be asked to understand JSON-LD at any point.

Consumers who do understand JSON-LD will see that this looks like a Linked Data Signature proof, and will find that it is in fact one and that it is documented in the expected manner.

This will also require an `@context`, which I am happy to help create to resolve JSON-LD normal custom JOSE/JWS interop issues...

**Comment by OR13** [comment]
Actually we will need to account for all the fields in the `proof` object... they should be mapped to JWS header... and the entire proof property should be removed.

We should ensure that the JWS header and proof properties match as part of verification since we are not relying on JSON-LD sigantures to do this for us.

**Comment by OR13** [comment]
While attempting to hack this up I am able to easily create a JSON-LD signed vc-json-schema:

```
 {
        "@context": [
          "https://w3id.org/did/v1",
          "https://web-payments.org/contexts/security-v2.jsonld",
          "https://w3c-ccg.github.io/vc-json-schemas/context/vc-json-schema-v0.0.jsonld"
        ],
        "name": "EmailCredentialSchema",
        "author": "did:work:MDP8AsFhHzhwUvGNuYkX7T",
        "authored": "2018-01-01T00:00:00+00:00",
        "schema": {
          "$schema": "http://json-schema.org/draft-07/schema#",
          "description": "Email",
          "type": "object",
          "properties": {
            "emailAddress": {
              "type": "string",
              "format": "email"
            }
          },
          "required": [
            "emailAddress"
          ],
          "additionalProperties": false
        },
        "proof": {
          "type": "Ed25519Signature2018",
          "created": "2019-12-09T06:02:19Z",
          "verificationMethod": "did:key:z6MkfXT3gnptvkda3fmLVKHdJrm8gUnmx3faSd1iVeCAxYtP",
          "proofPurpose": "assertionMethod",
          "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..i8zrTVVZaKoqev1ivmXJ2GvLZz-_CEW7h1VQmn2JyCzkjsd1w0pP78wb0T88nGsnJJai70bQsinSv-QMIe_VCg"
        }
      }
```

However, I am not able to verify it! 

```
{ verified: false,
        results:
         [ { proof: [Object], verified: false, error: [JsonLdError] } ],
        error:
         [ { jsonld.SyntaxError: Invalid JSON-LD syntax; "@value" value must not be an object or an array.
```

The value that fails with this error is:

```
{ '$schema': 'http://json-schema.org/draft-07/schema#',
        description: 'Email',
        type: 'object',
        properties: { emailAddress: { type: 'string', format: 'email' } },
        required: [ 'emailAddress' ],
        additionalProperties: false }
```

at _expandObject (node_modules/jsonld/lib/expand.js:760:13)

This is likely due to an error processing the `@json` type in the context for the vc-json-schema spec.

**Comment by OR13** [comment]
Attempting to sign this simpler object will also produce this error:

```
{"@context": [
    "https://w3id.org/did/v1",
    "https://web-payments.org/contexts/security-v2.jsonld",
    {
      "schema": "http://schema.org/",
      "name": "schema:name",
      "data": { "@id": "schema:data", "@type": "@json" }
    }
  ],
  "name": "Alice",
  "data": {
    "hello": 1,
    "foo": "bar"
  }}
```

Interesting the same error does not occur on the JSON-LD Playground when using RSA, but does when signing with Bitcoin...

```
{
  "@context": [
    {
      "@version": 1.1
    },
    "https://w3id.org/did/v1",
    "https://web-payments.org/contexts/security-v2.jsonld",
    {
      "schema": "http://schema.org/",
      "name": "schema:name",
      "data": {
        "@id": "schema:data",
        "@type": "@json"
      }
    },
    "https://w3id.org/security/v2"
  ],
  "name": "Alice",
  "data": {
    "hello": 1,
    "foo": "bar"
  },
  "proof": {
    "type": "RsaSignature2018",
    "created": "2019-12-09T06:13:52Z",
    "creator": "https://example.com/jdoe/keys/1",
    "domain": "json-ld.org",
    "jws": "eyJhbGciOiJQUzI1NiIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..GS0r0CGo3gi1xOrcu7x1KG8cs0bMWjTXBywMufxy2BU4qLpUZlJCpe9MsEIMBmtD-OE8d2PlqQ5hTIX-Bd0ZZlg2CVMr02XFKoy99mhE6OCqv_DZA0pAeN4lLkFtL9uF0_8d2Y83ya3EmQzPoS2mgLhtLjjGFz_KhKd4O6P10As",
    "nonce": "888b5106"
  }
}
```

@dlongley any advice on getting verify to work with this with Ed25519?

I have a test here which is failing: https://github.com/w3c-ccg/vc-json-schemas/blob/master/reference-impl/node-js/src/__tests__/jsonld.sanity.spec.js#L13

**Comment by dlongley** [comment]
@OR13,

Well, first, JSON literal support in jsonld.js (a 1.1 feature) was not yet fully implemented until this weekend. Combining the feature with signatures was definitely an issue. A new version of jsonld.js is being released today that may address some or all of the above problems.

Second, I'm not sure what version of jsonld-signatures is being used on the playground -- but the playground certainly didn't have full JSON literal support (for the above reasons). I'm going to ping @davidlehn to let us know when today's release can make it into the playground, etc., and then this stuff should be retested so we can go from there.

**Comment by dlongley** [comment]
@OR13 -- I do want to say that making the schema a JSON literal is the right way to go though... and that this should all work fine once the features and any bugs are sorted.

**Comment by OR13** [comment]
@glcohen I added a non jsonld example here... https://github.com/w3c-ccg/vc-json-schemas/blob/master/reference-impl/node-js/src/__tests__/no-jsonld.spec.js

The issue is that although what we are doing here is valid / safe (I think)... This is totally non standard approach, that yields something that looks like a JSON-LD Signature.

IMO we should pull this whole "Signature Suite" out of this repo since it does not have anything to do with vc-json-schema... if workday intends to use this kind of signature for other things, i suggest you host it and its documentation in a separate repo, as I have done for https://github.com/decentralized-identity/OpenPgpSignature2019

**Comment by OR13** [comment]
this is not safe... we need to json stringify deterministic until we an use https://tools.ietf.org/id/draft-rundgren-json-canonicalization-scheme-00.html

The input the JWS should be the json stringify of the credential without the jws...

**Comment by OR13** [comment]
fixed in https://github.com/w3c-ccg/vc-json-schemas/commit/a0392b4a65548bb4afa64b533e5cab5ad198fd74

**Comment by dlongley** [comment]
@OR13 note that jsonld.js uses the [canonicalize](https://www.npmjs.com/package/canonicalize) package (which implements JCS -- the RFC draft you linked to) when serializing JSON literals.

**Comment by OR13** [comment]
This works in the latest version of jsonld and jsondld-signatures, closing.
