### ISSUE TITLE
JSON Schema Canonicalization

### ISSUE THREAD

**Issue by decentralgabe** [w3c-ccg/vc-json-schemas#20]
Problem: two schemas with the same properties in different order, with all other properties constant, shouldn't be seen as different schemas. Can we canonicalize the schema?

Simply, at Workday, we've forced the alphabetization of the schema. Looking to hear what other's think.

**Comment by dlongley** [comment]
Not sure if you're asking a tooling question or not, but if so, the [canonicalize](https://www.npmjs.com/package/canonicalize) package implements [JCS](https://tools.ietf.org/html/draft-rundgren-json-canonicalization-scheme) and could be used to ensure two JSON schemas are the same regardless of property order.

**Comment by glcohen** [comment]
Thanks. Have other specs adopted JCS as a requirement for canonicalizing documents?

**Comment by OR13** [comment]
its used by JSON-LD for `@json` literals.

**Comment by OR13** [comment]
I used it in the example signature suite to support the non jsonld use case as well.

**Comment by vorth** [comment]
Property order is only the most obvious issue.  Two schemas can contain different `description` values and still describe the same data.  Also, I believe JSON Schema is extensible, so one schema may contain extension elements.  I don't think JCS is enough.

**Comment by decentralgabe** [comment]
This issue is no longer needed. Adding sections on both Data Integrity and JOSE style proofs which may themselves specify a canonicalization scheme.
