### ISSUE TITLE
Should bikeshed be used to define industry specific contexts

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/vc-json-schemas#21]
https://digitalbazaar.github.io/citizenship-vocab

This use case defines a context similar to the hypothetical trade-certificates context.

We could adopt a similar documentation pattern to get better alignment.

**Comment by msporny** [comment]
Ideally, we have a code generator driven from a UI that can generate the HTML, JSON-LD, JSON Schema, and anything else. I know that @gkellogg has tools in Ruby to convert a CSV file to a vocabulary document and all the RDF bits... we used it for the VC spec. Something like that, but with a UI and more polished.

**Comment by decentralgabe** [comment]
Should this stay open? Not sure if out of scope for this repo.

Also check out tree ldr - https://www.spruceid.dev/treeldr/treeldr-overview
