### ISSUE TITLE
fix spec hosting

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/vc-json-schemas#3]
Should the mardown file be renamed index.md / README.md so we can use built in github pages hosting?

https://w3c-ccg.github.io/vc-json-schemas/

**Comment by glcohen** [comment]
Sure, and maybe then use [bikeshed](https://github.com/tabatkins/bikeshed) for an index.html?

**Comment by OR13** [comment]
if we want to use bikeshed, we should add a README, with instructions to start using it. I'm not familiar with it, but I'm happy to use it.

**Comment by glcohen** [comment]
I can take a shot at that

**Comment by OR13** [comment]
@kimdhamilton  can you change the github pages hosting for this repo to use `docs` folder on master or give me permissions to do so?

**Comment by kimdhamilton** [comment]
I made both of you admins

**Comment by OR13** [comment]
This is now resolved, closing.

**Comment by kimdhamilton** [comment]
the repo creation scripts were in a bad state. Reopening and fixing

**Comment by kimdhamilton** [comment]
added files to this repo and fixed script
