### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ilanolkies** [w3c-ccg/vc-json-schemas#32]
https://github.com/w3c-ccg/vc-json-schemas/blob/de387ff4d6eb1aaf3880684dad566b911b12f7fa/spec/index.bs#L97

 Generic DID Parameter Name link is broken. Is it https://w3c.github.io/did-core/#did-syntax ?

Regards,

**Comment by glcohen** [comment]
Yes it is. Thank you, I can address this.

**Comment by ilanolkies** [comment]
My little contribution :)
