### ISSUE TITLE
Status of this repository?

### ISSUE THREAD

**Issue by awoie** [w3c-ccg/vc-json-schemas#51]
- is this still active?
- is there a latest rendered draft for JSON schema validation publish?
- why is the JSON schema validation only applied to the credentialSubject rather than the top-level VC object--note, one could extend the top-level VC object as well.

**Comment by glcohen** [comment]
It is in need of a new owner.

**Comment by tmarkovski** [comment]
> * is there a latest rendered draft for JSON schema validation publish?

https://w3c-ccg.github.io/vc-json-schemas/

> * why is the JSON schema validation only applied to the credentialSubject rather than the top-level VC object--note, one could extend the top-level VC object as well.

I'm curious about this, too. A top level schema would make more sense, as it doesn't restrict the VC validation only to `credentialSubject`, which is valid under the VC recommendation.
It's also unclear from the VC spec if the `credentialSchema` field refers to the top level VC schema or the `credentialSubject` only. This spec makes it clear it's the `credentialSubject` only, though not sure if this is just an interpretation.

Pinging @OR13

**Comment by glcohen** [comment]
I will work with Orie to get this updated.

My main goals:
1. Adopt the latest version of JSON Schema
2. Apply validation to the entire VC optionally

My thinking there is you really care about the data shape of the credentialSubject independently of the entire VC. Two schemas are necessary, and this is actually a practice we already adopted at Workday -- https://github.com/workdaycredentials/ledger-common/blob/master/credential/schema/verifiable-credential-schema.json

**Comment by glcohen** [comment]
Work happening here, PTAL https://github.com/w3c-ccg/vc-json-schemas/pull/52

**Comment by glcohen** [comment]
Closing as Draft 2, a work in progress has been published. Please open additional issues with specific requested improvements. Of course, PRs are welcome too!

https://w3c-ccg.github.io/vc-json-schemas/v2/index.html
