### ISSUE TITLE
Move JoseNonLinkedDataSignature2020 to a seperate repo

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/vc-json-schemas#6]
The non JSON-LD example relies on a signature suite that should be hosted and documented somewhere else.

Its also worth noting that the the signature suite approach taken for the non jsonld version is entirely custom, and not well documented or supported by existing VC libraries.

**Comment by OR13** [comment]
I have generalized the signature algorithm in this example repo here: https://github.com/transmute-industries/did-jose

This package is not published, and we (Transmute) are not committing to the name or support for is, but it might be helpful for reference.

**Comment by decentralgabe** [comment]
No longer relevant.
