### ISSUE TITLE
Matrix parameters :D

### ISSUE THREAD

**Issue by peacekeeper** [w3c-ccg/vc-json-schemas#80]
I LOVE how the specification contains DID URLs with matrix parameters, e.g.:

```
did:example:abcdefghi;id=17de181feb67447da4e78259d92d0240;version=1.0
```

Unfortunately, the DID WG decided to not support them in DID URL syntax for now, only reserve them for future use: https://www.w3.org/TR/did-core/#did-url-syntax

Therefore, the DID URLs in the specification should probably be updated to use query and/or fragment instead.

**Comment by glcohen** [comment]
Yeah I saw that! 😒 

Are you able to provide an example of your suggestion? 

The requirement is being able to surface author (DID), version, and identifier in the URI.

**Comment by glcohen** [comment]
Would `did:example:abcdefghi?schemaId=17de181feb67447da4e78259d92d0240&schemaVersion=1.0` work?
The problem is that the id and version properties are not in the DID Document, so it may be misleading 🤔

**Comment by bumblefudge** [comment]
devil's advocate, would `"id"="17de181feb67447da4e78259d92d0240"` work, or `"id"="urn:uuid:76e6e52b-681e-4952-b1f5-9b670144a5ba"` if someone opted out of that SHOULD? 😁

**Comment by glcohen** [comment]
> devil's advocate, would `"id"="17de181feb67447da4e78259d92d0240"` work, or `"id"="urn:uuid:76e6e52b-681e-4952-b1f5-9b670144a5ba"` if someone opted out of that SHOULD? 😁

like this?
`did:example:abcdefghi?id=urn:uuid:76e6e52b-681e-4952-b1f5-9b670144a5ba`

**Comment by bumblefudge** [comment]
hehe no, i mean like this:
`17de181feb67447da4e78259d92d0240`
or 
`urn:uuid:76e6e52b-681e-4952-b1f5-9b670144a5ba`
(ducks)

**Comment by glcohen** [comment]
@bumblefudge that's fine, it can be any identifier!

**Comment by clehner** [comment]
Here are two potential ways to resolve DID URLs to schema documents:
- Use DID [resource](https://wiki.trustoverip.org/display/HOME/DID+URL+Resource+Parameter+Specification) parameter. The DID itself identifies the schema document, through an indirection in the VDR.
e.g. `did:example:abcdefghi:17de181feb67447da4e78259d92d0240?resource=json&versionId=1`
or `did:example:17de181feb67447da4e78259d92d0240?resource=json&versionId=1`
- Use [DID Path](https://www.w3.org/TR/did-core/#path). The schema document is a resource under authority of the DID.
e.g. `did:example:abcdefghi/17de181feb67447da4e78259d92d0240?versionId=1`
or `did:example:abcdefghi/17de181feb67447da4e78259d92d0240/v1`.

Either way would need to be specified in the DID method specification.

**Comment by peacekeeper** [comment]
+1 to @clehner . DID URLs have many potential uses, and these are good examples!

**Comment by bumblefudge** [comment]
Thanks all!

**Comment by decentralgabe** [comment]
Matrix parameters handled here! https://github.com/w3c-ccg/vc-json-schemas/pull/102
