### ISSUE TITLE
JSON-LD cannot validate, only JSON Schema can

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c-ccg/vc-json-schemas#88]
JSON-LD is completely orthogonal to JSON Schema:
- JSON-LD cannot validate, JSON Schema can
- JSON-LD explicates JSON terms to URLs, and can add conveniences like datatype info, name graph, container (set/list), etc. JSON Schema doesn't

In addition, while the use of `credentialSchema` (in particular JSON Schema) is optional in VC, JSON-LD is necessary.

So I'm puzzled by these statements:

- https://w3c-ccg.github.io/vc-json-schemas/v2/index.html#drawbacks
>  A new version could be introduced that supports [JSON-LD] and removes support for [JSON_SCHEMA]. 
- https://w3c-ccg.github.io/vc-json-schemas/v2/index.html#alternatives
> [JSON-LD] is the most prominent alternative, though it does not provide the same functionality in regards to strict data validation

In particular, the latter should be changed to refer to the RDF Shape languages (SHACL and SHEX), which provide data validation features comparable to JSON Schema

Closely related to #16

**Comment by decentralgabe** [comment]
> So I'm puzzled by these statements:
> 
> * https://w3c-ccg.github.io/vc-json-schemas/v2/index.html#drawbacks
> 
> > A new version could be introduced that supports [JSON-LD] and removes support for [JSON_SCHEMA].

My intention, which I can see is less-than-clear, was to state that an LD schema could be embedded into a JSON schema so there's a 1 - 1 mapping between the two.

> * https://w3c-ccg.github.io/vc-json-schemas/v2/index.html#alternatives
> 
> > [JSON-LD] is the most prominent alternative, though it does not provide the same functionality in regards to strict data validation
> 
> In particular, the latter should be changed to refer to the RDF Shape languages (SHACL and SHEX), which provide data validation features comparable to JSON Schema

Yeah I wasn't really aware of these. They could be OK to add but seem quite complex and (potentially) unnecessary compared to JSON Schema which is quite widely adopted.

**Comment by VladimirAlexiev** [comment]
What is LD Schema?

If you don't like RDF Shapes then delete section Alternatives

**Comment by decentralgabe** [comment]
> What is LD Schema?

Any schema that uses JSON LD, like those here https://schema.org/docs/schemas.html

> If you don't like RDF Shapes then delete section Alternatives

My personal preferences have little to do with the specification. It would be dishonest to not share alternatives. If you believe there's an error, please make a contribution.

**Comment by decentralgabe** [comment]
Closing and will be handled in https://github.com/w3c-ccg/vc-json-schemas/issues/122
